Code Review Request "Hello Microverse" Pull Request
dev-mamun/Hello-Microverse pull request #4
Opened 2023-01-11 15:56 UTC by dev-mamun

It's a simple HTML & CSS project

2023-01-12 15:25 UTC, ABDULALI3468 requested changes
# Changes Required 👍 

Hi @dev-mamun, 

<img src="https://media1.giphy.com/media/VlqzeaRnhCvPLfrSh6/giphy.gif"/>

Great work on making the changes requested by a previous reviewer 👏 
You've done really well implementing some of the requested changes, but there are still some which aren't been addressed yet.


## Highlights 
✅All linters are checked.
✅Project is professionally documented.
✅The right GitHub flow method has been used.

 ## Required Changes ♻️

> 1- Please consider adding a professional summary to your Pull Request(PR) description. You can also have a look at the following [repository](https://github.com/ABDULALI3468/bookMe-frontend/pull/13) as a demonstration.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

> 1- Please consider adding a professional README file to the feature branch. You should use the following [Micorverse README Template](https://github.com/microverseinc/readme-template) You need to change it according to your respective project. Please don't delete any section from that template. Use all of them and remember the FAQ section is OPTIONAL. Remove the Logo and update the rest of README in accordance with your specific project.

As the previous CR forget to make as required changes. But still, it is very crucial for the professional repo. Please consider adding it.


## Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification.

> * This is My **GitHub**: ![GitHub followers](https://img.shields.io/github/followers/ABDULALI3468?label=ABDULALI&style=social)
> * This is My **Linkedin**: [![Linkedin Badge](https://img.shields.io/badge/-ABDUL%20ALI-blue?style=flat-square&logo=Linkedin&logoColor=white&link=https://www.linkedin.com/in/abdul-ali-5400bb216/)](https://www.linkedin.com/in/abdul-ali-5400bb216/)&nbsp;
> * This is My **Twitter**: [![Twitter Badge](https://img.shields.io/badge/-@mrabdul_ali_-1ca0f1?style=flat-square&labelColor=1ca0f1&logo=twitter&logoColor=white&link=https://twitter.com/mrabdul_ali)](https://twitter.com/mrabdul_ali)&nbsp;

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-12 16:17 UTC, dev-mamun commented
@ABDULALI3468 please check

2023-01-12 20:11 UTC, dev-mamun commented
@ABDULALI3468 please check

2023-01-13 10:14 UTC, dev-mamun commented
@ABDULALI3468 any update ?

2023-01-13 10:37 UTC, ABDULALI3468 commented
> @ABDULALI3468 any update ?

@dev-mamun For review, you need to go to the dashboard and ask for a review. Although you added a nice PR description still README is not according to the Microverse Template. You need to make it exactly in accordance with that. Please don't remove any sections from that. Remove Microverse Logo and FAQ section is OPTIONAL. If you are confused about [Microverse Template](https://github.com/microverseinc/readme-template) you can also consider the [implementation demo](https://github.com/ABDULALI3468/bookMe-frontend) of this template.

2023-01-13 12:06 UTC, didierganthier requested changes
Hi @dev-mamun ,

🎉 Great job on addressing the feedback from the previous review! You've made some solid progress in implementing the requested changes. However, there are still a few areas that need some attention before we can move on to the next project.

## Highlights
- Descriptive PR ✔️ 
- Linters passing ✔️ 
- Correct GitHub flow ✔️ 

<img src="https://media.giphy.com/media/qLWdMYX1NYF2g/giphy.gif" />

## Required Changes 🛠
- Please review the comments under the review for specific changes that still need to be made.

## Optional Suggestions 💡
- While these comments with the [OPTIONAL] prefix won't prevent the approval of this pull request, I strongly recommend taking them into account as they can improve your code. Some of them were missed by the previous reviewer and addressing them will really enhance your application.

🚀 Keep pushing forward, you're almost there! If you have any questions or need clarification on anything, feel free to leave a comment in the pull request thread and don't forget to tag me so I'll receive the notification.

**Please note**
- To avoid confusion and delays, please do not open a new pull request for re-reviews. Use the same pull request submitted for the first review, unless otherwise instructed.

------
As per the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561), you have a limited number of reviews per project. If you feel that the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s). 

Cheers and happy coding! 👏👏👏

2023-01-13 12:06 UTC, didierganthier commented on README.md
> +<p align="right">(<a href="#readme-top">back to top</a>)</p>
🎉 Great job on using the right `README.md` template provided by Microverse but make sure to remove the hardcoded sections such as `[key_feature_1]` to add yours, it could be something like:
```
header with color
```
This is just an example of course considering that not much was done in this project 🙂

2023-01-13 12:06 UTC, didierganthier commented on README.md
> +- [Live Demo Link](https://yourdeployedapplicationlink.com)
Considering that there's no live demo link for this project 👀 make sure to mention that in that section to avoid any confusion.

2023-01-13 12:06 UTC, didierganthier commented on README.md
> +<p align="right">(<a href="#readme-top">back to top</a>)</p>
This is a nice section to have 💯 but make sure to edit it to make it fit your project in order to make the README look even more professional, the prerequisites could mention stuff like:
- [ ] Having an IDE
- [ ] Having Git installed

The setup could mention information about cloning the project, there's no installation process for this so make sure to mention it, ✍🏽  same thing for the tests and deployment section. As for the usage, the user can just open the `index.html` file in any browser. 🌐

2023-01-13 12:06 UTC, didierganthier commented on README.md
> +<p align="right">(<a href="#readme-top">back to top</a>)</p>
Hey 👋🏽 make sure to take into account what I mentioned earlier for the key features section for this one too, this could go like:
```
Adding another header
```
I hope this helps 🙂

2023-01-13 12:06 UTC, didierganthier commented on README.md
> +<p align="right">(<a href="#readme-top">back to top</a>)</p>
Well done with this README 👏🏽  but this section is optional so in order to make it more reliable 🤩   if you're not gonna remove the hardcoded information, you may remove the whole section.

2023-01-13 12:06 UTC, didierganthier commented on README.md
> +I would like to thank...
Thank someone here 🙏🏽 it could be anyone who helped you make this project better, or it could be me 😅 , just make sure to mention someone here. NB: A lot of students just thank Microverse.

2023-01-13 12:06 UTC, didierganthier commented on README.md
> +
Hey 👋🏽 this note is purely for yourself and once you're done reading it it becomes useless for the rest of the README 📄, removing useless sections makes your README more reliable 🤓

2023-01-13 13:19 UTC, Debas-31 approved these changes
> ## Hi @dev-mamun   :wave:, 

# Status: Approved :heavy_check_mark: 

Great work on making the changes requested by a previous reviewer. Your project is complete !  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
<img src="https://media0.giphy.com/media/H1NIKdfygAAMruqArl/giphy.gif"/>


## Highlights
- Linters setup :heavy_check_mark:
- GitHub flow :heavy_check_mark: 
- PR title, PR summary, and README file :heavy_check_mark: 
- Commit message :heavy_check_mark:

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-13 19:50 UTC, merged